"""Streaming RAG chat endpoint.

The answer is generated by whichever LLM is available (resolve_provider): Anthropic when a
key is set, else a local Ollama model (keyless, offline). If neither is available, we still
return the relevant retrieved notes (retrieval is local/free). Never errors.

Responses are Server-Sent Events: each line is `data: {json}\n\n`.
"""

from __future__ import annotations

import json

from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

from ..rag import chain, retriever

router = APIRouter(tags=["chat"])


class ChatIn(BaseModel):
    message: str
    ticker_context: str | None = None
    conversation_history: list[dict] = []


class ChatConfigIn(BaseModel):
    provider: str | None = None       # "auto" | "anthropic" | "ollama"
    ollama_model: str | None = None


def _sse(obj: dict) -> str:
    return f"data: {json.dumps(obj)}\n\n"


def _chat_config() -> dict:
    from .. import config

    active = chain.resolve_provider()
    return {
        "provider_setting": config.get_llm_provider(),     # auto / anthropic / ollama
        "active": chain.provider_label(active),            # human label of what answers
        "active_provider": active,                          # anthropic / ollama / None
        "has_key": config.has_anthropic_key(),
        "ollama_available": chain._ollama_available(),
        "ollama_model": config.get_ollama_model(),
        "ollama_models": chain.ollama_models(),
    }


@router.get("/chat/config")
def get_chat_config() -> dict:
    return _chat_config()


@router.post("/chat/config")
def set_chat_config(cfg: ChatConfigIn) -> dict:
    from .. import config

    if cfg.provider in ("auto", "anthropic", "ollama"):
        config.set_llm_provider(cfg.provider)
    if cfg.ollama_model:
        config.set_ollama_model(cfg.ollama_model)
    return _chat_config()


@router.post("/chat")
def chat(req: ChatIn):
    context = chain.build_context(req.message, req.ticker_context)
    provider = chain.resolve_provider()  # 'anthropic' | 'ollama' | None
    vault_empty = retriever.is_empty()

    def gen():
        if provider:  # Claude or a local Ollama model — both write real answers
            try:
                for token in chain.stream_tokens(req.message, context, req.conversation_history, provider):
                    yield _sse({"token": token, "done": False})
            except Exception as exc:  # noqa: BLE001
                yield _sse({"token": f"\n\n[Error contacting the model: {exc}]", "done": False})
            if vault_empty:
                yield _sse({
                    "token": "\n\n💡 Connect your Obsidian vault to include your personal research in answers.",
                    "done": False,
                })
        else:
            # No LLM available (no key AND no local Ollama): surface retrieval only.
            if context["used_vault"]:
                msg = ("No language model is available, so I can't write a full answer — but here are "
                       "the most relevant notes from your vault:\n\n")
                for s in context["sources"]:
                    tag = f" ({s['ticker']})" if s.get("ticker") else ""
                    msg += f"• {s['filename']}{tag}\n"
                msg += ("\nFor reasoned answers free & offline, run a local model: `ollama run llama3`. "
                        "Or add an Anthropic API key.")
            else:
                msg = ("No language model is available. Run a local model for free, offline answers "
                       "(`ollama run llama3`), or add an Anthropic API key.")
            yield _sse({"token": msg, "done": False})

        yield _sse({
            "token": "",
            "done": True,
            "sources": context["sources"],
            "used_vault": context["used_vault"],
            "ai_generated": provider is not None,
            "provider": chain.provider_label(provider),
        })

    return StreamingResponse(gen(), media_type="text/event-stream")
